# Generated by Django 2.1.3 on 2018-11-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('fecha_ingreso', models.DateTimeField()),
                ('ID_ARRIENDO', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('ID_MOBIKE', models.AutoField(primary_key=True, serialize=False)),
                ('COORDENADAS', models.CharField(max_length=200)),
                ('QR', models.CharField(max_length=200)),
                ('ESTADO_CANDADO', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('RUT', models.CharField(max_length=200)),
                ('NOMBRECOMPLETO', models.CharField(max_length=200)),
                ('EDAD', models.IntegerField()),
                ('MEDIO_PAGO', models.CharField(choices=[('Debito', 'debito'), ('Credito', 'credito'), ('TarjetaMunicipal', 'tarjetamunicipal')], max_length=30)),
                ('NUM_CELULAR', models.CharField(max_length=200)),
                ('EMAIL', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='arriendo',
            name='ID_CLIENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobike.Cliente'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='ID_MOBIKE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobike.Bicicleta'),
        ),
    ]
