# Generated by Django 2.1.3 on 2018-11-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='NOMBRECOMPLETO',
            new_name='NOMBRE_COMPLETO',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='NUM_CELULAR',
            new_name='NUMERO_CELULAR',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='ESTADO_CANDADO',
            field=models.CharField(choices=[('Bloqueado', 'bloqueado'), ('Libre', 'libre')], max_length=200),
        ),
    ]
