# Generated by Django 2.1.3 on 2018-11-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobike', '0002_auto_20181113_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='fecha_ingreso',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='CODIGO_ARRIENDO',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='HORA_REGISTRO',
            field=models.TimeField(null=True),
        ),
    ]
