# Generated by Django 2.1.3 on 2018-11-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobike', '0003_auto_20181114_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='QR',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='CODIGO_BICICLETA',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
