# Generated by Django 2.1.3 on 2018-11-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobike', '0004_auto_20181114_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='CODIGO_ARRIENDO',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='CODIGO_BICICLETA',
            field=models.CharField(max_length=140),
        ),
    ]
